name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Directory to build Docker image from'
        required: true
        type: choice
        options:
          # Add image directories here!
          - 'fnm'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Parse Inputs
        id: parse_inputs
        run: |
          if [[ ! -f "src/${{ github.event.inputs.directory }}/Dockerfile" ]]; then
            echo "Directory src/${{ github.event.inputs.directory }} does not exist or does not contain a Dockerfile"
            exit 1
          fi
          IS_BETA=0
          if [[ ${{ github.ref }} != 'refs/heads/main' ]]; then
            IS_BETA=1
          fi
          echo "IS_BETA=$IS_BETA" >> $GITHUB_OUTPUT
          # version is based on the timestamp (JST)
          IMAGE_VERSION=$(if [[ $IS_BETA == 1 ]]; then echo "beta-"; fi)$(TZ=Asia/Tokyo date '+%Y%m%dT%H%M%S')
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_OUTPUT
          echo "IMAGE_NAME=${{ github.event.inputs.directory }}" >> $GITHUB_OUTPUT
      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: create metadata
        id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/${{ steps.parse_inputs.outputs.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable=${{ steps.parse_inputs.outputs.IS_BETA == 0 }}
            type=raw,value=${{ steps.parse_inputs.outputs.IMAGE_VERSION }}
            type=sha
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "src/${{ github.event.inputs.directory }}"
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          platforms: linux/amd64,linux/arm64
      - name: Add Tag to GitHub
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git tag -a ${{ steps.parse_inputs.outputs.IMAGE_VERSION }} -m "$(if [[ ${{ steps.parse_inputs.outputs.IS_BETA }} == 1 ]]; then echo 'Beta '; fi)Release ${{ steps.parse_inputs.outputs.IMAGE_VERSION }}"
          git push origin ${{ steps.parse_inputs.outputs.IMAGE_VERSION }}
